spring.application.name=dataFrame-prase
spring.application.version=1.0.0-SNAPSHOT

server.address=127.0.0.1
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
